spring.application.name=demo
spring.thymeleaf.cache=false
server.port=9090

# --------------------------
# Cau hinh Database MySQL
# --------------------------
# Ten driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# URL ket noi den tao o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore

#username=root(mac dinh cua paragon la root)
spring.datasource.username=root
# Mat khau (mac dinh cua paragon la rong)
spring.datasource.password=

# --------------------------
# Cau hinh JPA va Hibernate
# --------------------------
# Tu dong tao/cap nhat bang dua tren cac entity (Book, Category)
# Cac gia tri thong dung la: none, update, create, create-drop
spring.jpa.hibernate.ddl-auto=update
# Hien thi cau lenh SQL ra console
spring.jpa.show-sql=true
# Tat Open-in-View de tang performance (khong query database trong view rendering)
spring.jpa.open-in-view=false